insert into category (description) values ('American')
insert into category (description) values ('Italian')
insert into category (description) values ('Hungarian')
insert into category (description) values ('Fast food')
insert into unit_of_measure (unit_of_measure) values ('teaspoon')
insert into unit_of_measure (unit_of_measure) values ('tablespoon')
insert into unit_of_measure (unit_of_measure) values ('cup')
insert into unit_of_measure (unit_of_measure) values ('pinch')
insert into unit_of_measure (unit_of_measure) values ('ounce')